server:
  port: 8020

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # Route to Auth Service
        - id: auth-service
          uri: http://localhost:8021
          predicates:
            - Path=/api/v1/auth/**, /api/v1/tenants/register, /api/v1/tenants/confirm, /api/v1/tenants/lookup
            
        # Route to Employee Service (tenants other endpoints)
        - id: tenant-service-other
          uri: http://localhost:8022
          predicates:
            - Path=/api/v1/tenants, /api/v1/tenants/*/alert
            
        # Route to Employee Service (business endpoints)
        - id: employee-service
          uri: http://localhost:8022
          predicates:
            - Path=/api/v1/employees/**, /api/v1/departments/**, /api/v1/jobs/**

        # Route to Attendance Service
        - id: attendance-service
          uri: http://localhost:8023
          predicates:
            - Path=/api/v1/attendance/**, /api/v1/geofence/**

        # Route to Leave Service
        - id: leave-service
          uri: http://localhost:8024
          predicates:
            - Path=/api/v1/leave/**

        # Route to Payroll Service
        - id: payroll-service
          uri: http://localhost:8025
          predicates:
            - Path=/api/v1/payroll/**

        # Route to Claim Service
        - id: claim-service
          uri: http://localhost:8026
          predicates:
            - Path=/api/v1/claims/**

        # Route to Loan Service
        - id: loan-service
          uri: http://localhost:8027
          predicates:
            - Path=/api/v1/loans/**

        # Route to Performance Service
        - id: performance-service
          uri: http://localhost:8028
          predicates:
            - Path=/api/v1/performance/**

        # Route to Recruitment Service
        - id: recruitment-service
          uri: http://localhost:8029
          predicates:
            - Path=/api/v1/recruitment/**

        # Route to Asset Service
        - id: asset-service
          uri: http://localhost:8031
          predicates:
            - Path=/api/v1/assets/**

        # Route to Notification Service
        - id: notification-service
          uri: http://localhost:8032
          predicates:
            - Path=/api/v1/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: health, info
